<!DOCTYPE html>
<html>
    <head>
        <title>Catálogo de libros</title>
    </head>
    <body>
    	<h1>Catálogo de libros</h1>
        <table>
            <tr>
                <th>ID</th>
                <th>Título</th>
            </tr>
        {% for book in books %}
            <tr>
                <td>
                    <a href="/enli2012/public/books/show/{{ book['book_id'] }}">
                        Detalles
                    </a>
                </td>
                <td>{{ book['title'] }}s</td>
            <tr>
        {% endfor %}
        </table>
    </body>
</html>