<!DOCTYPE html>
<html>
    <head>
        <title>{{ book['title'] }}</title>
    </head>
    <body>
    	<h1>Detalle del libro</h1>
        <dl>
            <dt>Título</dt>
            <dd>{{ book['title'] }}</dd>
            <dt>Autor</dt>
            <dd>{{ book['author'] }}</dd>
        </dl>
        <p>
            <a href="/enli2012/public/books/list">Volver a la lista</a>
        </p>
    </body>
</html>